[package]
name = "simplemm"
version = "0.0.1"
authors = ["Kilian Kilger <kkilger@gmail.com>"]
edition = "2018"

[dependencies]
email-format = "~0.8.0"
email = "~0.0.21"
syslog = "^5.0"
daemonize = "~0.4.1"
toml = "~0.5"
diesel = { version = "~1.4.4", features = ["postgres","mysql"] }
